// Sample transactions for initial demo
export const SAMPLE_TRANSACTIONS = [
  {
    id: 1,
    title: 'March Salary',
    amount: 75000,
    category: 'Salary',
    date: new Date(2026, 2, 1).toISOString(),
    type: 'Income',
  },
  {
    id: 2,
    title: 'Grocery Shopping',
    amount: 5200,
    category: 'Food & Dining',
    date: new Date(2026, 2, 3).toISOString(),
    type: 'Expense',
  },
  {
    id: 3,
    title: 'Monthly Utility Bill',
    amount: 3500,
    category: 'Utilities',
    date: new Date(2026, 2, 5).toISOString(),
    type: 'Expense',
  },
  {
    id: 4,
    title: 'Freelance Project',
    amount: 15000,
    category: 'Freelance',
    date: new Date(2026, 2, 7).toISOString(),
    type: 'Income',
  },
  {
    id: 5,
    title: 'Movie Night',
    amount: 600,
    category: 'Entertainment',
    date: new Date(2026, 2, 8).toISOString(),
    type: 'Expense',
  },
  {
    id: 6,
    title: 'Car Fuel',
    amount: 2500,
    category: 'Transportation',
    date: new Date(2026, 2, 10).toISOString(),
    type: 'Expense',
  },
  {
    id: 7,
    title: 'Online Shopping',
    amount: 8500,
    category: 'Shopping',
    date: new Date(2026, 2, 12).toISOString(),
    type: 'Expense',
  },
  {
    id: 8,
    title: 'Doctor Visit',
    amount: 2000,
    category: 'Healthcare',
    date: new Date(2026, 2, 14).toISOString(),
    type: 'Expense',
  },
  {
    id: 9,
    title: 'Investment Returns',
    amount: 5000,
    category: 'Investment',
    date: new Date(2026, 2, 15).toISOString(),
    type: 'Income',
  },
  {
    id: 10,
    title: 'Restaurant Dinner',
    amount: 2200,
    category: 'Food & Dining',
    date: new Date(2026, 2, 16).toISOString(),
    type: 'Expense',
  },
  {
    id: 11,
    title: 'Flight Ticket',
    amount: 12000,
    category: 'Travel',
    date: new Date(2026, 2, 18).toISOString(),
    type: 'Expense',
  },
  {
    id: 12,
    title: 'Book Purchase',
    amount: 1500,
    category: 'Education',
    date: new Date(2026, 2, 20).toISOString(),
    type: 'Expense',
  },
];
